[project]
name = "pytester-utils"
version = "1.0.0"
description = "Powerful and ergonomic wrapper for pytester for your mental health."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pydantic~=2.13",
    "pytest~=9.1",
]

[dependency-groups]
dev = [
    "absolufy-imports~=0.3.1",
    "pre-commit~=4.6",
    "pytest-cov~=7.1",
    "ruff~=0.15.20",
    "ty~=0.0.56",
    "uv~=0.11.26",
]

[project.entry-points.pytest11]
pytester_utils = "pytester_utils._plugin"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["pytester_utils"]

[tool.hatch.build.targets.sdist]
packages = ["pytester_utils"]

[tool.uv]
cache-dir = "./.cache/uv"

[tool.pytest.ini_options]
cache_dir = "./.cache/pytest"
addopts = "--cov=src --cov-report=term --cov-report=xml --cov-branch"

[tool.ruff]
cache-dir = "./.cache/ruff"
line-length = 120

[tool.ruff.lint.per-file-ignores]
"./tests/**/*.py" = [
    "S101", # use of assert detected
]
"./pytester_utils/pytester_utils.py" = [
    "S101", # use of assert detected
]

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true # Allow `*args: Any` and `**kwargs: Any`.

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D100",    # Missing docstring in public module
    "D101",    # Missing docstring in public class
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D104",    # Missing docstring in public package
    "D105",    # Missing docstring in magic method
    "D106",    # Missing docstring in public nested class
    "D107",    # Missing docstring in public init
    "D203",    # Incompatible with D211
    "D212",    # Incompatible with D213
    "D413",    # Missing blank line at the end of a docstring,
    "FURB110", # Fix may modify behavior
    "RET504",  # Forbids assigning value to variable right before returning the variable, which is actually a common pattern in programming for ease of debugging.
    "TC001",   # Move first-party imports to type-checking block - python 3.15+ supports lazy imports, making this rule unnecessary
    "TC002",   # Move third-party imports to type-checking block - python 3.15+ supports lazy imports, making this rule unnecessary
    "TC003",   # Move standard library imports to type-checking block - python 3.15+ supports lazy imports, making this rule unnecessary
    "TD002",   # Missing todo author
    "PLC0415", # Import outside top level
    "FBT001", # Boolean-typed position argument in function definition
    "FBT002"
]
